# Generated by Django 3.2.9 on 2021-12-23 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_program_data', '0013_auto_20211223_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduled_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('day_times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_times', to='buddy_program_data.session_meeting_option')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reader', to=settings.AUTH_USER_MODEL)),
                ('sessions_scheduled', models.ManyToManyField(blank=True, related_name='scheduled_matches_in_session', to='buddy_program_data.Daily_Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Match',
                'verbose_name_plural': 'Scheduled Matches',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student_Match_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_needed', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_match_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Match Profile',
                'verbose_name_plural': 'Student Match Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Scheduled_Match_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_match_notes', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notes', to='matches.scheduled_match')),
            ],
            options={
                'verbose_name': 'Scheduled Match Note',
                'verbose_name_plural': 'Scheduled Match Notes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reader_Match_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('available_slots', models.ManyToManyField(blank=True, related_name='available', to='buddy_program_data.Reading_Session_Day_Time')),
                ('scheduled_slots', models.ManyToManyField(blank=True, related_name='scheduled', to='buddy_program_data.Reading_Session_Day_Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_match_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reader Match Profile',
                'verbose_name_plural': 'Reader Match Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
