# Generated by Django 3.2.9 on 2021-12-24 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0014_session_meeting_option_slot_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0002_auto_20211223_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Match Type',
                'verbose_name_plural': 'Match Types',
            },
        ),
        migrations.CreateModel(
            name='Temporary_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_type', to='matches.match_type')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_reader', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_session', to='buddy_program_data.daily_session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Match',
                'verbose_name_plural': 'Temporary Matches',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Temporary_Match_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_temp_match_notes', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_notes', to='matches.temporary_match')),
            ],
            options={
                'verbose_name': 'Temporary Match Note',
                'verbose_name_plural': 'Temporary Match Notes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='match_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='matches.match_type'),
        ),
    ]
