# Generated by Django 3.2.9 on 2021-12-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0014_session_meeting_option_slot_letter'),
        ('matches', '0003_auto_20211224_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader_match_profile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_semester', to='buddy_program_data.program_semester'),
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_semester', to='buddy_program_data.program_semester'),
        ),
        migrations.AddField(
            model_name='student_match_profile',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_semester', to='buddy_program_data.program_semester'),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_semester', to='buddy_program_data.program_semester'),
        ),
    ]
