# Generated by Django 3.2.9 on 2021-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20211224_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader_match_profile',
            name='open_slot_count',
            field=models.IntegerField(default=0, verbose_name='Open Count'),
        ),
        migrations.AddField(
            model_name='reader_match_profile',
            name='scheduled_slot_count',
            field=models.IntegerField(default=0, verbose_name='Scheduled Count'),
        ),
    ]
