# Generated by Django 3.2.9 on 2021-12-24 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_auto_20211224_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_match_profile',
            name='sch_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
