# Generated by Django 3.2.9 on 2021-12-24 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0006_student_match_profile_sch_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader_match_profile',
            name='sch_matches',
            field=models.ManyToManyField(blank=True, related_name='reader_stu', to=settings.AUTH_USER_MODEL),
        ),
    ]
