# Generated by Django 3.2.9 on 2021-12-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0014_session_meeting_option_slot_letter'),
        ('matches', '0007_reader_match_profile_sch_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_match',
            name='day_times',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_times', to='buddy_program_data.reading_session_day_time'),
        ),
    ]
