# Generated by Django 3.2.9 on 2021-12-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_scheduled_match_day_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader_match_profile',
            old_name='sch_matches',
            new_name='buddies',
        ),
        migrations.RenameField(
            model_name='student_match_profile',
            old_name='sch_match',
            new_name='buddy',
        ),
    ]
