# Generated by Django 3.2.9 on 2021-12-25 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0010_auto_20211224_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_match_notes', to=settings.AUTH_USER_MODEL)),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_type', to='matches.match_type')),
            ],
            options={
                'verbose_name': 'Match Note',
                'verbose_name_plural': 'Match Notes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='temporary_match_note',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='temporary_match_note',
            name='match',
        ),
        migrations.DeleteModel(
            name='Scheduled_Match_Note',
        ),
        migrations.DeleteModel(
            name='Temporary_Match_Note',
        ),
        migrations.AddField(
            model_name='scheduled_match',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='sch_match_notes', to='matches.Match_Note'),
        ),
        migrations.AddField(
            model_name='temporary_match',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='temp_match_notes', to='matches.Match_Note'),
        ),
    ]
