# Generated by Django 3.2.9 on 2021-12-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0017_alter_daily_session_session_end_date_time'),
        ('matches', '0011_auto_20211225_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Status_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Match Status Option',
                'verbose_name_plural': 'Match Status Option',
            },
        ),
        migrations.CreateModel(
            name='Match_Attendance_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_reassigned', models.BooleanField(default=False, verbose_name='M-R')),
                ('student_present', models.BooleanField(default=False, verbose_name='S-Present')),
                ('student_time_in', models.TimeField(blank=True, null=True)),
                ('student_time_out', models.TimeField(blank=True, null=True)),
                ('student_reassigned', models.BooleanField(default=False, verbose_name='S-R')),
                ('student_time_in_pending', models.IntegerField(blank=True, default=0, null=True)),
                ('student_time_in_breakout', models.IntegerField(blank=True, default=0, null=True)),
                ('volunteer_present', models.BooleanField(default=False, verbose_name='V-Present')),
                ('volunteer_time_in', models.TimeField(blank=True, null=True)),
                ('volunteer_time_out', models.TimeField(blank=True, null=True)),
                ('volunteer_reassigned', models.BooleanField(default=False, verbose_name='V-R')),
                ('volunteer_in_breakout_alone', models.IntegerField(blank=True, default=0, null=True)),
                ('volunteer_in_breakout_w_student', models.IntegerField(blank=True, default=0, null=True)),
                ('match_complete_at', models.TimeField(blank=True, null=True)),
                ('match_ended_at', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('match_successful', models.BooleanField(default=False, verbose_name='Success')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_attendance_type', to='matches.match_type')),
                ('notes', models.ManyToManyField(blank=True, related_name='match_attendance_notes', to='matches.Match_Note')),
                ('sch_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_match_attendance_record', to='matches.scheduled_match')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_attendance_session', to='buddy_program_data.daily_session')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_status', to='matches.match_status_option')),
                ('temp_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_attendance_record', to='matches.temporary_match')),
            ],
            options={
                'verbose_name': 'Match Attendance Record',
                'verbose_name_plural': 'Match Attendance Records',
                'ordering': ['session__date', 'session__day_time'],
            },
        ),
    ]
