# Generated by Django 3.2.9 on 2021-12-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0017_alter_daily_session_session_end_date_time'),
        ('matches', '0013_auto_20211226_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_match_profile',
            name='scheduled_slots',
            field=models.ManyToManyField(blank=True, related_name='student_scheduled', to='buddy_program_data.Reading_Session_Day_Time'),
        ),
    ]
