# Generated by Django 3.2.9 on 2021-12-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211215_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account Info',
                'verbose_name_plural': 'Users Account Info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Account_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('note_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_notes_written', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notes', to='users.user_account_info')),
            ],
            options={
                'verbose_name': 'User Account Note',
                'verbose_name_plural': 'User Account Notes',
                'ordering': ['id'],
            },
        ),
    ]
