# Generated by Django 3.2.9 on 2021-12-20 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_info_user_account_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('about_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_about', to=settings.AUTH_USER_MODEL)),
                ('note_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Note',
                'verbose_name_plural': 'User Notes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='user_account_note',
            name='note_by',
        ),
        migrations.RemoveField(
            model_name='user_account_note',
            name='user_account',
        ),
        migrations.DeleteModel(
            name='User_Account_Info',
        ),
        migrations.DeleteModel(
            name='User_Account_Note',
        ),
    ]
