# Generated by Django 3.2.9 on 2021-12-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211221_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Logout_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Logout Log',
                'verbose_name_plural': 'Login Logout Logs',
                'ordering': ['user__username'],
            },
        ),
    ]
