# Generated by Django 3.2.9 on 2021-12-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_login_logout_log_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_logout_log',
            name='user_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_session', to='users.user_session'),
        ),
    ]
