# Generated by Django 3.2.9 on 2021-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_login_logout_log_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logout_log',
            name='completed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
