# Generated by Django 3.2.9 on 2021-12-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_login_logout_log_user_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_logout_log',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='login_logout_log',
            name='user_session',
        ),
        migrations.CreateModel(
            name='Session_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_log', to='users.login_logout_log')),
                ('user_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_session', to='users.user_session')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['id'],
            },
        ),
    ]
