# Generated by Django 3.2.9 on 2021-12-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211225_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_log',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_log', to='users.login_logout_log'),
        ),
    ]
