# Generated by Django 3.2.9 on 2021-12-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_session_log_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session_log',
            options={'ordering': ['id'], 'verbose_name': 'Session Log', 'verbose_name_plural': 'Session Log'},
        ),
    ]
