# Generated by Django 3.2.9 on 2021-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_session_status',
            name='has_redirect',
            field=models.BooleanField(default=False, verbose_name='Redirect'),
        ),
    ]
