# Generated by Django 3.2.9 on 2021-12-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20211225_1547'),
        ('buddy_program_data', '0017_alter_daily_session_session_end_date_time'),
        ('reading_sessions', '0002_user_session_status_has_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Status_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Match Status Option',
                'verbose_name_plural': 'Match Status Option',
            },
        ),
        migrations.CreateModel(
            name='Match_Session_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status_active', models.BooleanField(default=True, verbose_name='Active')),
                ('member_reassigned', models.BooleanField(default=False, verbose_name='M-R')),
                ('reader_reassigned', models.BooleanField(default=False, verbose_name='R-R')),
                ('student_reassigned', models.BooleanField(default=False, verbose_name='S-R')),
                ('student_online', models.BooleanField(default=False, verbose_name='Student Online')),
                ('display_student_location', models.BooleanField(default=True)),
                ('reader_online', models.BooleanField(default=False, verbose_name='Reader Online')),
                ('display_reader_location', models.BooleanField(default=True)),
                ('both_online', models.BooleanField(default=False, verbose_name='Both Present')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('match_status_notes', models.ManyToManyField(blank=True, related_name='match_status_notes', to='matches.Match_Note')),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_status_type', to='matches.match_type')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_location', to='buddy_program_data.room')),
                ('sch_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_match_status', to='matches.scheduled_match')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_status_session', to='buddy_program_data.daily_session')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_option', to='reading_sessions.match_status_option')),
                ('temp_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_match_status', to='matches.temporary_match')),
            ],
            options={
                'verbose_name': 'Match Status',
                'verbose_name_plural': 'Match Statuses',
                'ordering': ['session__date', 'session__day_time', 'both_online'],
            },
        ),
    ]
