# Generated by Django 3.2.9 on 2021-12-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_match_attendance_record_match_status_option'),
        ('reading_sessions', '0003_match_session_status_match_status_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_session_status',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_option', to='matches.match_status_option'),
        ),
        migrations.DeleteModel(
            name='Match_Status_Option',
        ),
    ]
