# Generated by Django 3.2.9 on 2021-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0004_auto_20211226_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_session_status',
            name='reader_online',
            field=models.BooleanField(default=False, verbose_name='R-Online'),
        ),
        migrations.AlterField(
            model_name='match_session_status',
            name='student_online',
            field=models.BooleanField(default=False, verbose_name='S-Online'),
        ),
    ]
