# Generated by Django 3.2.9 on 2021-12-27 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20211226_0635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_sessions', '0005_auto_20211226_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_session_status',
            old_name='scheduled_match',
            new_name='active_scheduled_match',
        ),
        migrations.RenameField(
            model_name='user_session_status',
            old_name='logged_in',
            new_name='online',
        ),
        migrations.RemoveField(
            model_name='user_session_status',
            name='in_room_with_sch_buddy',
        ),
        migrations.RemoveField(
            model_name='user_session_status',
            name='in_room_with_temp_buddy',
        ),
        migrations.RemoveField(
            model_name='user_session_status',
            name='scheduled_buddy',
        ),
        migrations.RemoveField(
            model_name='user_session_status',
            name='temporary_buddy',
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='active_buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_buddy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='buddies',
            field=models.ManyToManyField(blank=True, related_name='all_buddies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='scheduled_matches',
            field=models.ManyToManyField(blank=True, related_name='sch_matches', to='matches.Scheduled_Match'),
        ),
    ]
