# Generated by Django 3.2.9 on 2021-12-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0008_help_request_reading_session_error_redirect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_session_status',
            old_name='online',
            new_name='online_jitsi',
        ),
        migrations.AddField(
            model_name='user_session_status',
            name='online_ws',
            field=models.BooleanField(default=False),
        ),
    ]
