# Generated by Django 3.2.9 on 2021-12-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0018_auto_20211228_0458'),
        ('reading_sessions', '0009_auto_20211230_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_session_status',
            name='room_jitsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_from_jitsi', to='buddy_program_data.room'),
        ),
    ]
