# Generated by Django 3.2.9 on 2021-12-30 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddy_program_data', '0018_auto_20211228_0458'),
        ('reading_sessions', '0010_user_session_status_room_jitsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_count', models.IntegerField(blank=True, default=0, null=True)),
                ('ws_count', models.IntegerField(blank=True, default=0, null=True)),
                ('jitsi_users', models.ManyToManyField(blank=True, related_name='users_jitsi', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='buddy_program_data.room')),
                ('ws_users', models.ManyToManyField(blank=True, related_name='users_ws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Participants',
                'verbose_name_plural': 'Room Participants',
            },
        ),
    ]
