# Generated by Django 3.2.9 on 2022-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0011_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_participants',
            name='occupied_jitsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_participants',
            name='occupied_ws',
            field=models.BooleanField(default=False),
        ),
    ]
