# Generated by Django 3.2.9 on 2022-01-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0013_alter_match_session_status_sch_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match_session_status',
            options={'ordering': ['session__date', 'session__day_time', 'both_online'], 'verbose_name': 'Match Session Status', 'verbose_name_plural': 'Match Session Statuses'},
        ),
    ]
