# Generated by Django 3.2.9 on 2022-01-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0014_alter_match_session_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_session_status',
            name='all_connected',
            field=models.BooleanField(default=False),
        ),
    ]
