# Generated by Django 3.2.9 on 2021-12-15 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('videofile', models.FileField(upload_to=registration.models.volunteer_videos, verbose_name='')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_video', to='registration.volunteer_registration')),
            ],
            options={
                'verbose_name': 'Volunteer Video',
                'verbose_name_plural': 'Volunteer Videos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer_Registration_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_screening', models.CharField(blank=True, choices=[('Not Attempted', 'Not Attempted'), ('Attempted-Failed', 'Attempted But Failed'), ('Attempted-Passed', 'Passed')], max_length=30, null=True, verbose_name='Tech Screening')),
                ('online_training_completed', models.BooleanField(default=False)),
                ('video_uploaded', models.BooleanField(default=False)),
                ('video_reviewed', models.BooleanField(default=False)),
                ('live_screening', models.BooleanField(default=False)),
                ('orientation', models.BooleanField(default=False)),
                ('reference_check', models.BooleanField(default=False)),
                ('approved_to_match', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vols_approved', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vols_last_updated', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registration_status', to='registration.volunteer_registration')),
            ],
            options={
                'verbose_name': 'Volunteer Registration Status',
                'verbose_name_plural': 'Volunteer Registration Statuses',
                'ordering': ['id'],
            },
        ),
    ]
