# Generated by Django 3.2.9 on 2021-12-16 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_volunteer_registration_status_volunteer_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer_registration_status',
            old_name='live_screening',
            new_name='live_screening_passed',
        ),
        migrations.CreateModel(
            name='Registration_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_notes', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='registration.volunteer_registration')),
            ],
            options={
                'verbose_name': 'Registration Note',
                'verbose_name_plural': 'Registration Notes',
                'ordering': ['id'],
            },
        ),
    ]
