# Generated by Django 3.2.9 on 2021-12-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_registration_note_volunteer_registration_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer_registration_note',
            options={'ordering': ['id'], 'verbose_name': 'Volunteer Registration Note', 'verbose_name_plural': 'Volunteer Registration Notes'},
        ),
    ]
