# Generated by Django 3.2.9 on 2021-12-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_volunteer_registration_note_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_Websocket_Error',
            new_name='Registration_Error',
        ),
        migrations.AlterModelOptions(
            name='registration_error',
            options={'ordering': ['-created'], 'verbose_name': 'Registration Error', 'verbose_name_plural': 'Registration Errors'},
        ),
    ]
