# Generated by Django 3.2.9 on 2021-12-17 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_auto_20211216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_registration_note',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_registration_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student_Registration_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsive', models.BooleanField(default=False)),
                ('confirm', models.BooleanField(default=False)),
                ('tech_screening', models.CharField(blank=True, choices=[('Not Attempted', 'Not Attempted'), ('Attempted-Failed', 'Attempted But Failed'), ('Attempted-Passed', 'Passed')], max_length=30, null=True, verbose_name='Tech Screening')),
                ('approved_to_match', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_approved', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_last_updated', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration_status', to='registration.student_registration')),
            ],
            options={
                'verbose_name': 'Student Registration Status',
                'verbose_name_plural': 'Student Registration Statuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student_Registration_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_registration_notes', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='registration.student_registration')),
            ],
            options={
                'verbose_name': 'Student Registration Note',
                'verbose_name_plural': 'Student Registration Notes',
                'ordering': ['id'],
            },
        ),
    ]
