# Generated by Django 3.2.9 on 2021-12-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20211217_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_video',
            name='times_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Parent_Registration_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_registration_notes', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='registration.parent_registration')),
            ],
            options={
                'verbose_name': 'Parent Registration Note',
                'verbose_name_plural': 'Parent Registration Notes',
                'ordering': ['id'],
            },
        ),
    ]
