# Generated by Django 3.2.9 on 2021-12-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20211217_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration_status',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration_status', to='registration.student_registration'),
        ),
        migrations.AlterField(
            model_name='volunteer_registration_status',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registration_status', to='registration.volunteer_registration'),
        ),
    ]
