# Generated by Django 3.2.9 on 2021-12-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20211217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_video',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_video', to='registration.volunteer_registration'),
        ),
    ]
