# Generated by Django 3.2.9 on 2021-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_volunteer_video_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_registration_status',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved'),
        ),
    ]
