# Generated by Django 3.2.9 on 2021-12-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0012_volunteer_registration_status_date_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_registration_status',
            name='date_denied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date denied'),
        ),
        migrations.AddField(
            model_name='volunteer_registration_status',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer_registration_status',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vols_denied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_registration_status',
            name='tech_screening',
            field=models.CharField(blank=True, choices=[('Not Attempted', 'Not Attempted'), ('Failed', 'Failed'), ('Passed', 'Passed')], max_length=30, null=True, verbose_name='Tech Screening'),
        ),
        migrations.AlterField(
            model_name='volunteer_registration_status',
            name='tech_screening',
            field=models.CharField(blank=True, choices=[('Not Attempted', 'Not Attempted'), ('Failed', 'Failed'), ('Passed', 'Passed')], max_length=30, null=True, verbose_name='Tech Screening'),
        ),
    ]
