# Generated by Django 3.2.9 on 2021-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20211219_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_registration_status',
            name='denied_reason',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
