# Generated by Django 3.2.9 on 2021-12-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0014_volunteer_registration_status_denied_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration_status',
            name='date_waitlist',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date waitlisted'),
        ),
        migrations.AddField(
            model_name='student_registration_status',
            name='waitlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_registration_status',
            name='waitlist_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stus_waitlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
