# Generated by Django 3.2.9 on 2021-12-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20211219_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration_status',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved'),
        ),
        migrations.AddField(
            model_name='student_registration_status',
            name='waitlist_reason',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
