# Generated by Django 3.2.9 on 2021-12-20 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0019_auto_20211220_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
