# Generated by Django 3.2.9 on 2021-12-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import phonenumber_field.modelfields
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0005_alter_question_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0023_auto_20211221_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=16, null=True, region=None)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('in_school', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('current_school', models.CharField(blank=True, max_length=150, null=True)),
                ('fluent_spanish', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('computer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('cropped_profile_image', models.ImageField(blank=True, null=True, upload_to=registration.models.staff_profile_images)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=registration.models.staff_temp_images)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('current_education_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_current_class', to='buddy_program_data.current_education_class')),
                ('current_education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_current_level', to='buddy_program_data.current_education_level')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_device', to='buddy_program_data.device_type')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_gender', to='buddy_program_data.gender')),
                ('highest_education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_highest_education', to='buddy_program_data.current_education_level')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Registration',
                'verbose_name_plural': 'Staff Registrations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff_Registration_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_registration_notes', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='registration.staff_registration')),
            ],
            options={
                'verbose_name': 'Staff Registration Note',
                'verbose_name_plural': 'Staff Registration Notes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff_Registration_IP_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_valid', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('ws_connected', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_reg_ip', to='registration.staff_registration')),
            ],
            options={
                'verbose_name': 'Staff Registration IP Info',
                'verbose_name_plural': 'Staff Registration IP Info',
                'ordering': ['id'],
            },
        ),
    ]
