# Generated by Django 3.2.9 on 2021-12-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
