# Generated by Django 3.2.9 on 2021-12-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_registration_reg_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
