# Generated by Django 3.2.9 on 2021-12-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jitsi_Data_Websocket_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_in_function', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_for_user', models.CharField(blank=True, max_length=255, null=True)),
                ('error_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Jitsi Data Websocket Error',
                'verbose_name_plural': 'Jitsi Data Websocket Errors',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Jitsi_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_jid', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('instance_created', models.DateTimeField(auto_now_add=True, verbose_name='instance created')),
            ],
            options={
                'verbose_name': 'Jitsi Room',
                'verbose_name_plural': 'Jitsi Rooms',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jitsi_Room_Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('jitsi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_jid', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('instance_created', models.DateTimeField(auto_now_add=True, verbose_name='instance created')),
            ],
            options={
                'verbose_name': 'Jitsi Room Occupant',
                'verbose_name_plural': 'Jitsi Room Occupants',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jitsi_User_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('in_room', models.BooleanField(default=False)),
                ('room_jid', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_email', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_jid', models.CharField(blank=True, max_length=255, null=True)),
                ('occupant_joined_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('occupant_left_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('instance_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('instance_updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'Jitsi User Event',
                'verbose_name_plural': 'Jitsi User Event',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jitsi_User_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'Jitsi User Status',
                'verbose_name_plural': 'Jitsi User Status',
                'ordering': ['id'],
            },
        ),
    ]
