# Generated by Django 3.2.9 on 2021-12-12 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jitsi_data', '0001_initial'),
        ('buddy_program_data', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitsi_user_status',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jitsi_user_event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to='buddy_program_data.room'),
        ),
        migrations.AddField(
            model_name='jitsi_user_event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jitsi_room_occupant',
            name='jitsi_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_room', to='jitsi_data.jitsi_room'),
        ),
        migrations.AddField(
            model_name='jitsi_room_occupant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jitsi_room',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_room', to='buddy_program_data.room'),
        ),
    ]
