# Generated by Django 3.2.9 on 2021-12-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddy_program_data', '0018_auto_20211228_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Chat_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_in_function', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_for_user', models.CharField(blank=True, max_length=255, null=True)),
                ('error_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Staff Chat Error',
                'verbose_name_plural': 'Staff Chat Errors',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Staff_Chat_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Chat Room',
                'verbose_name_plural': 'Staff Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='Staff_Room_Unread_Chat_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0, verbose_name='Unread Count')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_unread_staff', to='staff_chat.staff_chat_room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unread_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Chat Uread Message',
                'verbose_name_plural': 'Staff Chat Unread Messages',
            },
        ),
        migrations.CreateModel(
            name='Staff_Room_Chat_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('meeting_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages', to='buddy_program_data.room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_chat.staff_chat_room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Chat Room Message',
                'verbose_name_plural': 'Staff Chat Room Messages',
            },
        ),
    ]
