# Generated by Django 3.2.9 on 2021-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0003_response_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_flag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
