# Generated by Django 3.2.9 on 2021-12-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0005_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('offset', models.IntegerField(blank=True, help_text='-240 DST, -300 no DST', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_on_day', to='buddy_program_data.day')),
            ],
            options={
                'verbose_name': 'Server Time',
                'verbose_name_plural': 'Server Times',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('times', models.ManyToManyField(blank=True, related_name='server_times', to='buddy_program_data.Server_Time')),
            ],
        ),
    ]
