# Generated by Django 3.2.9 on 2021-12-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0006_server_schedule_server_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_schedule',
            options={'ordering': ['name'], 'verbose_name': 'Server Schedule', 'verbose_name_plural': 'Server Schedules'},
        ),
    ]
