# Generated by Django 3.2.9 on 2021-12-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0008_alter_server_schedule_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_semester',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='days_in_session', to='buddy_program_data.Day'),
        ),
        migrations.AddField(
            model_name='program_semester',
            name='full_dates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program_semester',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Reading_Session_Day_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('session_slot', models.CharField(max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_program_data.day')),
            ],
            options={
                'verbose_name': 'Session Day/Time',
                'verbose_name_plural': 'Session Days/Times',
                'ordering': ['day__number', 'session_slot'],
            },
        ),
        migrations.AddField(
            model_name='program_semester',
            name='day_time_slots',
            field=models.ManyToManyField(blank=True, related_name='semester_day_time', to='buddy_program_data.Reading_Session_Day_Time'),
        ),
    ]
