# Generated by Django 3.2.9 on 2021-12-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0009_auto_20211223_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_With_Daily_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_program_data.day')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_day', to='buddy_program_data.program_semester')),
            ],
            options={
                'verbose_name': 'Day With Daily Sessions',
                'verbose_name_plural': 'Days With Daily Sessions',
                'ordering': ['date'],
            },
        ),
    ]
