# Generated by Django 3.2.9 on 2021-12-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0010_day_with_daily_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_with_daily_session',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
