# Generated by Django 3.2.9 on 2021-12-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0011_day_with_daily_session_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_with_daily_session',
            name='all_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='percent_successful',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='total_active_scheduled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='total_complete_reading_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='total_complete_scheduled_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='total_temporary',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Daily_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_session', models.BooleanField(default=False, verbose_name='Archived')),
                ('session_start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Date/Time')),
                ('session_end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Date/Time')),
                ('student_entry_allowed_start', models.DateTimeField(blank=True, null=True)),
                ('student_entry_allowed_end', models.DateTimeField(blank=True, null=True)),
                ('session_complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('day_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_day_time', to='buddy_program_data.reading_session_day_time')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to='buddy_program_data.program_semester')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['date', 'day_time'],
            },
        ),
        migrations.AddField(
            model_name='day_with_daily_session',
            name='day_sessions',
            field=models.ManyToManyField(blank=True, related_name='day_sessions', to='buddy_program_data.Daily_Session'),
        ),
    ]
