# Generated by Django 3.2.9 on 2021-12-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0013_auto_20211223_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_meeting_option',
            name='slot_letter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
