# Generated by Django 3.2.9 on 2022-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0018_auto_20211228_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_time',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
