# Generated by Django 3.2.9 on 2022-01-13 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddy_program_data', '0019_server_time_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mega_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mega_coordinator', to=settings.AUTH_USER_MODEL)),
                ('team_leaders', models.ManyToManyField(blank=True, related_name='mega_team_leaders', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='mega_team_vol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mega Team',
                'verbose_name_plural': 'Mega Teams',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('meeting_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week', to='buddy_program_data.day')),
                ('mega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mega_team', to='buddy_program_data.mega_team')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_room', to='buddy_program_data.room')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='team_vols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buddy_program_data.day')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='buddy_program_data.team')),
            ],
            options={
                'verbose_name': 'Team Meeting',
                'verbose_name_plural': 'Team Meetings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Day_With_Team_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('server_on', models.TimeField(blank=True, null=True)),
                ('server_off', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_program_data.day')),
                ('day_meetings', models.ManyToManyField(blank=True, related_name='day_meetings', to='buddy_program_data.Team_Meeting')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_meetings', to='buddy_program_data.program_semester')),
            ],
            options={
                'verbose_name': 'Day With Team Meeting',
                'verbose_name_plural': 'Day With Team Meetings',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Day_With_Orientation_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('allowed_participants', models.ManyToManyField(blank=True, related_name='orientation_allowed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day With Orientation Meeting',
                'verbose_name_plural': 'Day With Orientation Meetings',
                'ordering': ['date'],
            },
        ),
    ]
