# Generated by Django 3.2.9 on 2022-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0020_day_with_orientation_meeting_day_with_team_meeting_mega_team_team_team_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
