# Generated by Django 3.2.9 on 2022-01-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0021_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='buddy_program_data.mega_team'),
        ),
    ]
