# Generated by Django 3.2.9 on 2022-01-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_program_data', '0022_alter_team_mega'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='meeting_day_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_time', to='buddy_program_data.team_meeting_time'),
        ),
    ]
